const relics = [
    { name: "Akabeko", description: "Au début de chaque combat, la première attaque que vous jouez inflige 8 points de dégâts supplémentaires.",image: './src/images/Reliques/Akabeko.png' },
    { name: "Burning Blood", description: "Restaure 6 PV à la fin de chaque combat.", image: './src/images/Reliques/BurningBlood.png' },
    { name: "Vajra", description: "Augmente ta Force de 1.", image: './src/images/Reliques/Vajra.png' },
    { name: "Oddly Smooth Stone", description: "Augmente ta Dexterité de 1.", image: "./src/images/Reliques/OddlySmoothStone.png" },
    { name: "Pen Nib", description: "Tous les 10 tours, ton attaque fait le double de dégâts.", image: './src/images/Reliques/PenNib.png' },
    { name: "Ice Cream", description: "Garde ton Énergie entre les tours.", image: './src/images/Reliques/IceCream.png' },
    { name: "Anchor", description: "Commence chaque combat avec 10 points de Bloque.", image: './src/images/Reliques/Anchor.png' },
    { name: "Bag of Marbles", description: "Applique Vulnérable à tous les ennemis au début du combat.", image: './src/images/Reliques/BagofMarbles.png' },
    { name: "Paper Krane", description: "Les ennemis avec Faible infligent 40 % de dégâts en moins au lieu de 25 %.", image: './src/images/Reliques/PaperCrane.png' },
    { name: "Paper Frog", description: "Les ennemis vulnérables reçoivent 75 % de dégâts supplémentaires au lieu de 50 %.", image: './src/images/Reliques/PaperFrog.png' },
    { name: "Singing Bowl", description: "Permet de gagner +2 PV max au lieu de prendre une carte.", image: './src/images/Reliques/SingingBowl.png' },
    { name: "Strawberry", description: "Augmente les PV max de 7.", image: './src/images/Reliques/Strawberry.png' },
    { name: "Toxic Egg", description: "Chaque fois que vous ajoutez une carte de compétence à votre deck, elle est améliorée .", image: './src/images/Reliques/ToxicEgg2.png' },
    { name: "Molten Egg", description: "Chaque fois que vous ajoutez une carte d'attaque à votre deck, elle est améliorée .", image: "./src/images/Reliques/MoltenEgg2.png" },
    { name: "Frozen Egg", description: "Chaque fois que vous ajoutez une carte de pouvoir à votre deck, elle est améliorée .", image: "./src/images/Reliques/FrozenEgg2.png" },
    { name: "Old Coin", description: "Ajoute 300 pièces d'or.", image: './src/images/Reliques/OldCoin.png' },
    { name: "Orichalcum", description: "Si tu n'as pas de Bloque, gagne 6 Bloque à la fin de ton tour.", image: './src/images/Reliques/Orichalcum.png' },
    { name: "Girya", description: "Augmente ta Force de 1 après chaque campfire.", image: './src/images/Reliques/Girya.png' },
    { name: "Magic Flower", description: "Augmente les soins de 50 % si tu n'es pas un personnage Ironclad.", image: './src/images/Reliques/MagicFlower.png' },
    { name: "Pandora's Box", description: "Une fois ramasser, Transformez toutes les frappes et défenses .", image: './src/images/Reliques/PandorasBox.png' },
    { name: "Shovel", description: "Permet de creuser pour une relique dans les feux de camps.", image: './src/images/Reliques/Shovel.png' },
    { name: "Tiny Chest", description: "Chaque 4ème pièce ? est une salle au trésor.", image: './src/images/Reliques/TinyChest.png' },
    { name: "Maw Bank", description: "Gagne 12 pièces d'or après chaque combat tant que tu ne passes pas par un magasin.", image: './src/images/Reliques/MawBank.png' },
    { name: "Busted Crown", description: "Gagnez 1 Énergie au début de chaque tour. Sur les écrans de récompenses de cartes, vous avez le choix entre 2 cartes de moins.", image: './src/images/Reliques/BustedCrown.png' },
    { name: "Dead Branch", description: "À chaque carte épuisée, crée une carte aléatoire dans ta main.", image: './src/images/Reliques/DeadBranch.png' },
    { name: "Meal Ticket", description: "Soigne 15 PV chaque fois que tu entres dans une boutique.", image: './src/images/Reliques/MealTicket.png' },
    { name: "Omamori", description: "Préserve des malédictions pour deux fois.", image: './src/images/Reliques/Omamori.png' },
    { name: "Red Skull", description: "Si tes PV sont sous les 50%, gagne +3 Force.", image: './src/images/Reliques/RedSkull.png' },
    { name: "Snake Skull", description: "Après avoir appliqué du poison, ajoutez 1 poison supplémentaire.", image: "./src/images/Reliques/SnakeSkull.png" },
    { name: "Stone Calendar", description: "Au 7e tour, inflige 52 dégâts à tous les ennemis.", image: './src/images/Reliques/StoneCalendar.png' },
    { name: "Turnip", description: "Vous ne pouvez plus devenir fragile.", image: './src/images/Reliques/Turnip.png' },
    { name: "Ginger", description: "Vous ne pouvez plus devenir affaibli .", image: "./src/images/Reliques/Ginger.png" },
    { name: "Gold-Plated Cables", description: "Double l’effet de ton Le plus à Droite.", image: './src/images/Reliques/Cables.png' },
    { name: "Dolly's Mirror", description: "Choisis une carte dans ton deck et crée une copie de cette carte.", image: './src/images/Reliques/DollysMirror.png' },
    { name: "Hand Drill", description: "Les ennemis gagnent 2 Vulnérable lorsque tu brises leur Bloque.", image: './src/images/Reliques/HandDrill.png' },
    { name: "Meat on the Bone", description: "Si tes PV sont sous 50% à la fin d’un combat, soigne 12 PV.", image: './src/images/Reliques/MeatontheBone.png' },
    { name: "Orange Pellets", description: "À chaque fois que vous jouez un pouvoir, une attaque et une compétence au cours du même tour, supprimez tous vos débuffs.", image: './src/images/Reliques/OrangePellets.png' },
    { name: "Regal Pillow", description: "Soigne +15 PV en plus aux feux de camp.", image: './src/images/Reliques/RegalPillow.png' },
    { name: "Strange Spoon", description: "Les cartes éphémères ont une chance de ne pas être épuisées.", image: './src/images/Reliques/StrangeSpoon.png' },
    { name: "Twisted Funnel", description: "Applique 4 Poison à tous les ennemis au début du combat.", image: './src/images/Reliques/TwistedFunnel.png' },
    { name: "Ancient Tea Set", description: "Chaque fois que vous entrez dans un feu de camp , démarrez le prochain combat avec 2 énergies supplémentaires ", image: './src/images/Reliques/AncientTeaSet.png' },
    { name: "Calipers", description: "Au début de votre tour, perdez 15 Blocs plutôt que la totalité de vos Blocs .", image: './src/images/Reliques/Calipers.png' },
    { name: "Dream Catcher", description: "Permet de choisir une carte lorsque tu te reposes à un feu de camp.", image: './src/images/Reliques/DreamCatcher.png' },
    { name: "Happy Flower", description: "Tous les 3 tours, gagnez 1 Énergie .", image: './src/images/Reliques/HappyFlower.png' },
    { name: "Medical Kit", description: "Les cartes de statut injouables peuvent désormais être jouées. Jouer une carte de statut épuisera la carte.", image: './src/images/Reliques/MedicalKit.png' },
    { name: "Ring of the Snake", description: "Vous pouvez voir les cartes de la prochaine main de votre adversaire.", image: "./src/images/Reliques/RingoftheSnake.png" },
    { name: "Ring of the Serpent", description: "Remplace l'Anneau du Serpent . Au début de votre tour, piochez 1 carte supplémentaire.", image: './src/images/Reliques/RingoftheSerpent.png' },
    { name: "Unceasing Top", description: "Lorsque tu n'as plus de cartes en main, pioche une carte.", image: './src/images/Reliques/UnceasingTop.png' },
    { name: "Art of War", description: "Si tu n’as pas joué d’attaques durant ton tour, gagne 1 Énergie au prochain tour.", image: './src/images/Reliques/ArtofWar.png' },
    { name: "Calling Bell", description: "Lors du ramassage, obtenez une malédiction unique et 3 reliques.", image: './src/images/Reliques/CallingBell.png' },
    { name: "Du-Vu Doll", description: "Pour chaque Malédiction dans ton deck, augmente ta Force de 1.", image: './src/images/Reliques/Du-VuDoll.png' },
    { name: "Holy Water", description: "Au début du combat, ajoute trois cartes Miracle dans ta main.", image: './src/images/Reliques/Holy_water.png' },
    { name: "Melange", description: "À chaque fois que vous mélangez votre pile de pioche, Scrutez 3.", image: './src/images/Reliques/Melange.png' },
    { name: "Runic Dome", description: "Gagnez 1 Énergie au début de chaque tour. Vous ne pouvez plus voir les intentions ennemies ..", image: './src/images/Reliques/RunicDome.png' },
    { name: "The Specimen", description: "Chaque fois qu'un ennemi meurt, transférez tout poison qu'il possède à un ennemi aléatoire.", image: './src/images/Reliques/TheSpecimen.png' },
    { name: "The Boot", description: "Si tu gagnes des points de Bloque, tu fais 3 dégâts supplémentaires.", image: './src/images/Reliques/Boot.png' },
    { name: "Bottled Lightning", description: "Une fois ramassé, choisissez une carte Compétence . Commencez chaque combat avec cette carte en main", image: './src/images/Reliques/BottledLightning.png' },
    { name: "Bottled Flame", description: "Une fois ramassé, choisissez une carte d'Attaque . Commencez chaque combat avec cette carte en main", image: './src/images/Reliques/BottledFlame.png' },
    { name: "Bottled Tornado", description: "Une fois ramassé, choisissez une carte Pouvoir . Commencez chaque combat avec cette carte en main", image: './src/images/Reliques/BottledTornado.png' },
    { name: "Eternal Feather", description: "Pour chaque 5 cartes dans votre deck, soignez 3 PV à chaque fois que vous entrez dans un feu de camp .", image: './src/images/Reliques/EternalFeather.png' },
    { name: "Pure Water", description: "Au début du combat, ajoute une carte de Miracle dans ta main.", image: './src/images/Reliques/PureWater-0.png' },
    { name: "Mark of the Bloom", description: "Tu ne peux plus guérir.", image: './src/images/Reliques/MarkoftheBloom.png' },
    { name: "Necronomicon", description: "La première attaque jouée à chaque tour qui coûte 2 ou plus est jouée deux fois. Lorsque vous prenez cette relique, vous devenez Maudit .", image: './src/images/Reliques/Necronomicon.png' },
    { name: "Enchiridion", description: "Au début de chaque combat, ajoutez une carte Pouvoir aléatoire à votre main. Son coût est de 0 jusqu'à la fin du tour.", image: "./src/images/Reliques/Enchiridion.png" },
    { name: "Nilry's Codex", description: "À chaque tour, choisis une carte à ajouter à ton deck.", image: './src/images/Reliques/NilrysCodex.png' },
    { name: "Sundial", description: "Toutes les 3 fois que vous mélangez votre pioche, gagnez 2 Énergie .", image: './src/images/Reliques/Sundial.png' },
    { name: "The Red Mask", description: "Au début de chaque combat, vous appliquez 1 Faiblesse à TOUS les ennemis.", image: './src/images/Reliques/RedMask.png' },
    { name: "Damaru", description: "Au début de votre tour, gagnez 1 Mantra.", image: './src/images/Reliques/Damaru.png' },
    { name: "Matryoshka", description: "Lorsque tu obtiens une relique, obtient une relique supplémentaire.", image: './src/images/Reliques/Matryoshka.png' },
    { name: "Golden Idol", description: "Vous obtenez 25% d'or supplémentaire en éliminant vos ennemis.", image: './src/images/Reliques/GoldenIdol.png' },
    { name: "Bloody Idol", description: "Lorsque vous gagnez de l'or, vous récupérez 5 PV.", image: './src/images/Reliques/BloodyIdol.png' },
    { name: "Gambling Chip", description: "Au début de chaque combat, vous défaussez autant de cartes que vous le souhaitez, puis en piochez le même nombre.", image: './src/images/Reliques/GamblingChip.png' },
    { name: "Black Blood", description: "Remplace Sang ardent. À la fin du combat, vous récupérez 10 PV.", image: './src/images/Reliques/BlackBlood.png' },
    { name: "Runnic Capacitor", description: "Commencez chaque combat avec 3 emplacements d'orbes supplémentaires.", image: './src/images/Reliques/RunicCapacitor.png' },
    { name: "Odd Mushroom", description: "Lorsque vous êtes vulnérable, subissez 25 % de dégâts supplémentaires au lieu de 50.", image: "./src/images/Reliques/OddMushroom.png" },
    { name: "Astrolabe", description: "Quand ramassé, choisissez et transformez 3 cartes, puis améliorez-les.", image: "./src/images/Reliques/Astrolabe.png" },
    { name: "Hovering Kite", description: "La première fois que vous défaussez une carte à chaque tour, gagnez 1 Énergie .", image: "./src/images/Reliques/HoveringKite.png" },
    { name: "Coffee Dripper", description: "Gagnez 1 Énergie au début de chaque tour. Vous ne pouvez plus vous reposer au feux de camps.", image: "./src/images/Reliques/CoffeeDripper.png" },
    { name: "Fusion Hammer", description: "Gagnez 1 Énergie au début de chaque tour. Vous ne pouvez plus forger aux feux de camps.", image: "./src/images/Reliques/FusionHammer.png" },
    { name: "Circlet", description: "Collectez-en autant que vous le pouvez.", image: "./src/images/Reliques/Circlet.png" },
    { name: "CloakClasp", description: "À la fin de votre tour, gagnez 1 blocage pour chaque carte dans votre main. ", image: "./src/images/Reliques/CloakClasp.png" },
    { name: "ClockworkSouvenir", description: "Au début de chaque combat, gagnez 1 artefact. ", image: "./src/images/Reliques/ClockworkSouvenir.png" },
    { name: "CultistMask", description: "Vous vous sentez plus bavard.", image: "./src/images/Reliques/CultistMask.png" },
    { name: "Gremlin Mask", description: "Commencez chaque combat avec 1 Faiblesse.", image: './src/images/Reliques/GremlinMask.png' },
    { name: "Nloth's Mask", description: "Le prochain coffre non-boss que vous ouvrez est vide.", image: "./src/images/Reliques/NlothsMask.png" },
    { name: "SsserpentHead", description: "À chaque fois que vous entrez dans une salle ?, gagnez 50 pièces d'or.", image: "./src/images/Reliques/SsserpentHead.png" },
    { name: "Face of Cleric", description: "Augmentez vos PV max de 1 après chaque combat.", image: "./src/images/Reliques/FaceOfCleric.png" },
    { name: "Peace Pipe", description: "Vous pouvez désormais retirer des cartes de votre deck dans les feux de camps.", image: "./src/images/Reliques/PeacePipe.png" },
    { name: "Smiling Mask", description: "Le service de retrait de carte du commerçant coûte désormais toujours 50 pièces d'or .", image: "./src/images/Reliques/SmilingMask.png" },
    { name: "Bird-Faced Urn", description: "À chaque fois que vous jouez un Pouvoir , soignez 2 PV.", image: "./src/images/Reliques/BirdFacedUrn.png" },
    { name: "Black Star", description: "Lorsque vous battez un élite, obtenez un relique supplémentaire.", image: "./src/images/Reliques/BlackStar.png" },
    { name: "Blood Vial", description: "Au début de chaque combat, soignez 2 PV.", image: "./src/images/Reliques/BloodVial.png" },
    { name: "Kunai", description: "Chaque fois que vous jouez 3 cartes d'attaque en un tour, gagnez 1 force.", image: "./src/images/Reliques/Kunai.png" },
    { name: "Shuriken", description: "Chaque fois que vous jouez 3 cartes d'attaque en un tour, gagnez 1 force.", image: "./src/images/Reliques/Shuriken.png" },
    { name: "Ornamental Fan", description: "Chaque fois que vous jouez 3 attaques en un seul tour, gagnez 4 blocs .", image: "./src/images/Reliques/OrnamentalFan.png" },
    { name: "Nunchaku", description: "Gagnez 1 Énergie chaque fois que vous jouez 10 attaques.", image: "./src/images/Reliques/Nunchaku.png" },
    { name: "Ninja Scroll", description: "Commencez chaque combat avec 3 Surins en main.", image: "./src/images/Reliques/NinjaScroll.png" },
    { name: "Blue Candle", description: "Les cartes Malédiction peuvent désormais être jouées. Jouer une Malédiction vous fera perdre 1 PV et épuisera la carte.", image: "./src/images/Reliques/BlueCandle.png" },
    { name: "Brimstone", description: "Au début de votre tour, gagnez 2 Force et TOUS les ennemis gagnent 1 Force.", image: "./src/images/Reliques/Brimstone.png" },
    { name: "BronzeScales", description: "Chaque fois que vous subissez des dégâts, vous en renvoyez 3.", image: "./src/images/Reliques/BronzeScales.png" },
    { name: "Captain's Wheel", description: "Au début de votre 3ème tour, gagnez 18 Blocage .", image: "./src/images/Reliques/Captain_wheel.png" },
    { name: "Cauldron", description: "Une fois récupéré, ramassez 5 potions aléatoires .", image: "./src/images/Reliques/Cauldron.png" },
    { name: "Centennial Puzzle", description: "La première fois que vous perdez des PV à chaque combat, piochez 3 cartes.", image: "./src/images/Reliques/CentennialPuzzle.png" },
    { name: "Ceramic Fish", description: "À chaque fois que vous ajoutez une carte à votre deck, gagnez 9 pièces d'or.", image: "./src/images/Reliques/CeramicFish.png" },
    { name: "Champion Belt", description: "Chaque fois que vous appliquez Vulnérable , appliquez également 1 Faiblesse .", image: "./src/images/Reliques/ChampionBelt.png" },
    { name: "Charon's Ashes", description: "À chaque fois que vous épuisez une carte, infligez 3 dégâts à TOUS les ennemis", image: "./src/images/Reliques/CharonsAshes.png" },
    { name: "Chemical X", description: "À chaque fois que vous jouez une carte coûtant X, ses effets sont augmentés de 2.", image: "./src/images/Reliques/ChemicalX.png" },
    { name: "Darkstone Periapt", description: "Chaque fois que vous obtenez une malédiction , augmentez vos PV max de 6.", image: "./src/images/Reliques/DarkstonePeriapt.png" },
    { name: "Data Disk", description: "Commencez chaque combat avec 1 Concentration .", image: "./src/images/Reliques/DataDisk.png" },
    { name: "Ectoplasm", description: "Vous ne pouvez pas gagner d'or. Au début de chaque combat, gagnez 1 d'énergie.", image: "./src/images/Reliques/Ectoplasm.png" },
    { name: "Emotion Chip", description: "Si vous avez perdu des PV lors du tour précédent, déclenchez la capacité passive de tous les Orbes au début de votre tour.", image: "./src/images/Reliques/EmotionChip.png" },
    { name: "Empty Cage", description: "Lors de la récupération, retirez 2 cartes de votre Deck.", image: "./src/images/Reliques/EmptyCage.png" },
    { name: "Pocketwatch", description: "À chaque fois que vous jouez 3 cartes ou moins au cours d'un tour, piochez 3 cartes supplémentaires au début de votre prochain tour.", image: "./src/images/Reliques/Pocketwatch.png" },
    { name: "Sling of Courage", description: "Commencez chaque combat d'élite avec 2 points de force.", image: "./src/images/Reliques/Sling.png" },
    { name: "Snecko Eye", description: "Piochez 2 cartes supplémentaires à chaque tour. Commencez chaque combat en étant confus .", image: "./src/images/Reliques/SneckoEye.png" },
    { name: "Sozu", description: "Gagnez 1 Énergie au début de chaque tour. Vous ne pouvez plus obtenir de potions .", image: "./src/images/Reliques/Sozu.png" },
    { name: "Spirit Poop", description: "C'est désagréable.", image: "./src/images/Reliques/SpiritPoop.png" },
    { name: "Strike Dummy", description: "Les cartes contenant « Frappe » infligent 3 dégâts supplémentaires.", image: "./src/images/Reliques/StrikeDummy.png" },
    { name: "Symbiotic Virus", description: "Au début de chaque combat, canalisez 1 Obscurité .", image: "./src/images/Reliques/SymbioticVirus.png" },
    { name: "Tear Drop Locket", description: "Commencez chaque combat dans le calme.", image: "./src/images/Reliques/Tear_drop_locket.png" },
    { name: "Duality", description: "À chaque fois que vous jouez une attaque, gagnez 1 point de Dextérité temporaire .", image: "./src/images/Reliques/Yang-0.png" },
    { name: "Golden Eye", description: "À chaque fois que vous Scrutez, Scrutez 2 cartes supplémentaires.", image: "./src/images/Reliques/Golden_eye.png" },
    { name: "Philosopher's Stone", description: "Gagnez 1 Énergie au début de chaque tour. TOUS les ennemis commencent avec +1 Force .", image: "./src/images/Reliques/PhilosophersStone.png" },
    { name: "Mutagenic Strength", description: "Commencez chaque combat avec 3 points de Force qui sont perdus à la fin de votre tour.", image: "./src/images/Reliques/MutagenicStrength.png" },
    { name: "Runic Pyramid", description: "À la fin de votre tour, toutes les cartes que vous n'avez pas jouées restent dans votre main.", image: "./src/images/Reliques/RunicPyramid.png" },
    { name: "Sacred Bark", description: "Doublez l'efficacité de vos potions.", image: "./src/images/Reliques/SacredBark.png" },
    { name: "Self-Forming Clay", description: "À chaque fois que vous perdez des PV au combat, gagnez 3 Blocages au tour suivant.", image: "./src/images/Reliques/SelfFormingClay.png" },
    { name: "Tingsha", description: "Chaque fois que vous défaussez une carte, infligez 3 points de dégâts à un ennemi aléatoire.", image: "./src/images/Reliques/Tingsha.png" },
    { name: "Prismatic Shard", description: "Les cartes des autres classes peuvent maintenant apparaître dans vos récompenses.", image: "./src/images/Reliques/PrismaticShard.png" },
    { name: "Question Card", description: "Ajoute un choix de carte supplémentaire lors des récompenses.", image: "./src/images/Reliques/QuestionCard.png" },
    { name: "Tiny House", description: "Obtenez 50 pièces d'or, améliorez une carte, gagnez 5 PV, ajoutez une carte à votre deck et recevez une potion.", image: "./src/images/Reliques/TinyHouse.png" },
    { name: "Slavers Collar", description: "Pendant les combats de boss et d'élite, obtenez 1 énergie supplémentaire au début de chaque tour.", image: "./src/images/Reliques/SlaversCollar.png" },
    { name: "Thread and Needle", description: "Au début de chaque combat, gagnez 4 points d'armure plaquée .", image: "./src/images/Reliques/ThreadandNeedle.png" },
    { name: "Tungsten Rod", description: "À chaque fois que vous perdez des PV, perdez-en 1 de moins.", image: "./src/images/Reliques/TungstenRod.png" },
    { name: "Torii", description: "Chaque fois que vous devez recevoir 5 ou moins de dégâts d'attaque non bloqués , réduisez-les à 1.", image: "./src/images/Reliques/Torii.png" },
    { name: "Ink Bottle", description: "À chaque fois que vous jouez 10 cartes, piochez 1 carte.", image: "./src/images/Reliques/InkBottle.png" },
    { name: "Lizard Tail", description: "Lorsque vous devez mourir, soignez à la place 50 % de vos PV max (ne fonctionne qu'une fois).", image: "./src/images/Reliques/LizardTail.png" },
    { name: "Incense Burner", description: "Tous les 6 tours, gagnez 1 Intangible.", image: "./src/images/Reliques/IncenseBurner.png" },
    { name: "Prayer Wheel", description: "Les ennemis normaux lâchent une récompense de carte supplémentaire.", image: "./src/images/Reliques/PrayerWheel.png" },
    { name: "Runic Cube", description: "À chaque fois que vous perdez des PV, piochez 1 carte.", image: "./src/images/Reliques/RunicCube.png" },
    { name: "Mark of Pain", description: "Gagnez 1 Énergie au début de chaque tour. Commencez les combats avec 2 Blessures dans votre pioche.", image: "./src/images/Reliques/MarkofPain.png" },
    { name: "Cursed Key", description: "Gagnez 1 Énergie au début de chaque tour. À chaque fois que vous ouvrez un coffre non-boss , obtenez une Malédiction .", image: "./src/images/Reliques/CursedKey.png" },
    { name: "Mango", description: "Augmente votre maximum de PV de 14.", image: "./src/images/Reliques/Mango.png" },
    { name: "Mercury Hourglass", description: "Au début de votre tour, infligez 3 dégâts à TOUS les ennemis.", image: "./src/images/Reliques/MercuryHourglass.png" },
    { name: "Mummified Hand", description: "À chaque fois que vous jouez un Pouvoir , une carte aléatoire dans votre main coûte 0 pour le tour.", image: "./src/images/Reliques/MummifiedHand.png" },
    { name: "Lantern", description: "Gagnez 1 Énergie au premier tour de chaque combat.", image: "./src/images/Reliques/Lantern.png" },
    { name: "Lees Waffle", description: "Augmentez vos PV max de 7 et soignez tous vos PV.", image: "./src/images/Reliques/LeesWaffle.png" },
    { name: "Letter Opener", description: "Chaque fois que vous jouez 3 compétences en un seul tour, infligez 5 points de dégâts à TOUS les ennemis.", image: "./src/images/Reliques/LetterOpener.png" },
    { name: "Pantograph", description: "Au début des combats contre les boss , soignez 25 PV.", image: "./src/images/Reliques/Pantograph.png" },
    { name: "Warped Tongs", description: "Au début de votre tour, améliorez une carte aléatoire dans votre main pour le reste du combat.", image: "./src/images/Reliques/WarpedTongs.png" },
    { name: "Whetstone", description: "Quand ramasser, améliorez 2 attaques aléatoires .", image: "./src/images/Reliques/Whetstone.png" },
    { name: "War Paint", description: "Quand ramasser, améliorez 2 compétences aléatoires .", image: "./src/images/Reliques/WarPaint.png" },
    { name: "Wrist Blade", description: "Les attaques qui coûtent 0 infligent 4 dégâts supplémentaires.", image: "./src/images/Reliques/WristBlade.png" },
    { name: "Frozen Core", description: "Remplace Cracked Core . Si vous terminez votre tour avec des emplacements d'orbes vides, canalisez 1 givre.", image: "./src/images/Reliques/FrozenCore.png" },
    { name: "Nloth's Gift", description: "Triple les chances de recevoir des cartes rares en guise de récompenses de monstre.", image: "./src/images/Reliques/NlothsGift.png" },
    { name: "Bag of Preparation", description: "Au début de votre combat, commencez avec 2 cartes supplémentaires.", image: "./src/images/Reliques/BagofPreparation.png" },
    { name: "Frozen Eye", description: "Lorsque vous consultez votre pile de pioche, les cartes sont désormais affichées dans l'ordre.", image: "./src/images/Reliques/FrozenEye.png" },
    { name: "Inserter", description: "Tous les 2 tours, gagnez 1 emplacement d'orbe.", image: "./src/images/Reliques/Inserter.png" },
    { name: "Gremlin Horn", description: "À chaque fois qu'un ennemi meurt, gagnez 1 Énergie et piochez 1 carte.", image: "./src/images/Reliques/GremlinHorn.png" },
    { name: "Horn Cleat", description: "Au début de votre 2ème tour, gagnez 14 Blocage .", image: "./src/images/Reliques/Horn_cleat.png" },
    { name: "Membership Card", description: "50% de réduction sur tous les produits !", image: "./src/images/Reliques/MembershipCard.png" },
    { name: "Orrery", description: "Choisissez et ajoutez 5 cartes à votre deck.", image: "./src/images/Reliques/Orrery.png" },
    { name: "Preserved Insect", description: "Les ennemis dans les salles Élite ont 25 % de PV en moins.", image: "./src/images/Reliques/PreservedInsect.png" },
    { name: "The Courier", description: "Le marchand ne manque plus de cartes , de reliques ou de potions et ses prix sont réduits de 20 %.", image: "./src/images/Reliques/TheCourier.png" },
    { name: "Tough Bandages", description: "À chaque fois que vous défaussez une carte pendant votre tour, gagnez 3 Blocage ", image: "./src/images/Reliques/ToughBandages.png" },
    { name: "Toy Ornithopter", description: "À chaque fois que vous utilisez une potion , soignez 5 PV.", image: "./src/images/Reliques/ToyOrnithopter.png" },
    { name: "Violet Lotus", description: "À chaque fois que vous quittez le Calme , gagnez une Énergie supplémentaire .", image: "./src/images/Reliques/Violet_lotus.png" },
    { name: "White Beast Statue", description: "Vous obtenez toujours une Potion après un combat.", image: "./src/images/Reliques/WhiteBeastStatue.png" },
    { name: "Winged Greaves", description: "Vous pouvez ignorer les chemins lorsque vous choisissez la prochaine pièce à parcourir 3 fois.", image: "./src/images/Reliques/WingedGreaves.png" },
    { name: "Toolbox", description: "Au début de chaque combat, choisissez 1 des 3 cartes incolores aléatoires et ajoutez la carte choisie dans votre main.", image: "./src/images/Reliques/Toolbox.png" },
    { name: "Potion Belt", description: "Une fois ramasser, obtenez 2 emplacements de potion.", image: "./src/images/Reliques/PotionBelt.png" },
    { name: "Neow's Lament", description: "Les ennemis de vos 3 premiers combats auront 1 PV.", image: "./src/images/Reliques/NeowsLament.png" },
    { name: "Nuclear Battery", description: "Au début de chaque combat, canalisez 1 Plasma.", image: "./src/images/Reliques/NuclearBattery.png" },
    { name: "Velvet Choker", description: "Gagnez 1 Énergie au début de chaque tour. Vous ne pouvez pas jouer plus de 6 cartes par tour.", image: "./src/images/Reliques/VelvetChoker.png" },
    { name: "Cracked Core ", description: "Au début de chaque combat, canalisez 1 Lightning.", image: "./src/images/Reliques/CrackedCore.png" },
    { name: "Juzu Bracelet", description: "Les combats ennemis réguliers ne se déroulent plus dans les salles ? .", image: "./src/images/Reliques/JuzuBracelet.png" },
    { name: "Pear", description: "Lors du ramassage, augmentez vos PV max de 10.", image: "./src/images/Reliques/Pear.png" },
    { name: "The Abacus", description: "Gagnez 6 Blocs à chaque fois que vous mélangez votre pioche.", image: "./src/images/Reliques/TheAbacus.png" },
    
];

export default relics;
